// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC3QjxVO3U8fNZawlnFj4V0GlNibRGf3o',
    appId: '1:939523940329:web:ade397a5e19770f1f03578',
    messagingSenderId: '939523940329',
    projectId: 'sabibom-app',
    authDomain: 'sabibom-app.firebaseapp.com',
    storageBucket: 'sabibom-app.firebasestorage.app',
    measurementId: 'G-TVF4CTQZ8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo4Hxkq1tfdEreugEuLkAOE0RPNUctSSk',
    appId: '1:939523940329:android:9c1a8cd7ef0a07e5f03578',
    messagingSenderId: '939523940329',
    projectId: 'sabibom-app',
    storageBucket: 'sabibom-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu08mBUMFxc_5f6KXiZLNzAnYdObg8sRg',
    appId: '1:939523940329:ios:efa375ae09f6f8e5f03578',
    messagingSenderId: '939523940329',
    projectId: 'sabibom-app',
    storageBucket: 'sabibom-app.firebasestorage.app',
    iosBundleId: 'com.sabibom.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu08mBUMFxc_5f6KXiZLNzAnYdObg8sRg',
    appId: '1:939523940329:ios:efa375ae09f6f8e5f03578',
    messagingSenderId: '939523940329',
    projectId: 'sabibom-app',
    storageBucket: 'sabibom-app.firebasestorage.app',
    iosBundleId: 'com.sabibom.app',
  );
}
