/** Server-only platform collections (Admin SDK). Client rules deny all. */
export const COLLECTIONS = {
  users: "users",
  businesses: "businesses",
  feedback: "feedback",
  sabiUnanswered: "sabi_unanswered",
  apiRateLimits: "api_rate_limits",
  notificationEvents: "notification_events",
  platformAdmins: "platform_admins",
  platformAdminActivity: "platform_admin_activity",
  platformMetricsDaily: "platform_metrics_daily",
  platformSettings: "platform_settings",
  platformFeatureFlags: "platform_feature_flags",
  platformAnnouncements: "platform_announcements",
  platformAppVersions: "platform_app_versions",
  platformAiRequests: "platform_ai_requests",
  platformSecurityEvents: "platform_security_events",
  supportTickets: "support_tickets",
  bugReports: "bug_reports",
  backupJobs: "platform_backup_jobs",
  restoreJobs: "platform_restore_jobs",
  importJobs: "platform_import_jobs",
  deletionRequests: "platform_deletion_requests",
  notifications: "platform_notifications",
  betaTesters: "platform_beta_testers",
  subscriptionPlans: "subscription_plans",
  businessSubscriptions: "business_subscriptions",
  billingEvents: "billing_events",
  scheduledJobs: "platform_scheduled_jobs",
} as const;

export const SETTINGS_DOCS = {
  public: "public",
  general: "general",
  ai: "ai",
  featureFlags: "feature_flags",
  maintenance: "maintenance",
  announcements: "announcements",
  appVersions: "app_versions",
  platform: "platform",
  aiProviders: "ai_providers",
  systemHealth: "system_health",
  releaseReadiness: "release_readiness",
} as const;
