/**
 * Permission codes aligned with Flutter AppPermission.
 */
export const APP_PERMISSIONS = [
  "create_sale",
  "view_own_sales",
  "view_all_sales",
  "view_sale_details",
  "share_receipt",
  "print_receipt",
  "apply_discount",
  "override_price",
  "void_sale",
  "refund_sale",
  "view_products",
  "manage_products",
  "archive_product",
  "adjust_stock",
  "view_inventory_movements",
  "view_cost_price",
  "manage_categories",
  "manage_units",
  "view_product_expiry",
  "manage_product_expiry",
  "dispose_expired_stock",
  "view_product_profit",
  "view_product_potential_profit",
  "export_expiry_report",
  "export_product_profit_report",
  "view_customers",
  "manage_customers",
  "view_customer_balance",
  "record_customer_payment",
  "adjust_customer_balance",
  "archive_customer",
  "view_expenses",
  "create_expense",
  "edit_expense",
  "void_expense",
  "manage_expense_categories",
  "view_suppliers",
  "manage_suppliers",
  "create_purchase",
  "view_purchases",
  "record_supplier_payment",
  "create_purchase_return",
  "view_supplier_balance",
  "view_purchase_costs",
  "view_sales_reports",
  "view_expense_reports",
  "view_inventory_reports",
  "view_customer_reports",
  "view_supplier_reports",
  "view_profit",
  "export_reports",
  "manage_receipt_templates",
  "edit_business_branding",
  "download_receipt_pdf",
  "share_receipt_pdf",
  "use_sabi",
  "use_sabi_sales",
  "use_sabi_expenses",
  "use_sabi_purchases",
  "ask_sabi_business_questions",
  "ask_sabi_profit_questions",
  "edit_business_settings",
  "manage_staff",
  "manage_roles",
  "view_staff_activity",
  "approve_sensitive_actions",
  "view_branch",
  "manage_branches",
  "switch_branch",
  "view_all_branches",
  "view_combined_reports",
  "assign_staff_to_branches",
  "manage_branch_operations",
  "view_notifications",
  "manage_notification_preferences",
  "view_low_stock_alerts",
  "view_customer_debt_alerts",
  "view_supplier_payment_alerts",
  "view_approval_notifications",
  "view_end_of_day_alerts",
  "view_daily_summary",
  "view_weekly_report",
  "receive_push_notifications",
  "send_customer_reminder_draft",
  "view_staff_notifications",
] as const;

export type AppPermissionCode = (typeof APP_PERMISSIONS)[number];

const ROLE_DEFAULTS: Record<string, AppPermissionCode[]> = {
  owner: [...APP_PERMISSIONS],
  manager: [
    "create_sale",
    "view_own_sales",
    "view_all_sales",
    "view_sale_details",
    "share_receipt",
    "print_receipt",
    "apply_discount",
    "override_price",
    "void_sale",
    "refund_sale",
    "view_products",
    "manage_products",
    "archive_product",
    "adjust_stock",
    "view_inventory_movements",
    "view_cost_price",
    "manage_categories",
    "manage_units",
    "view_product_expiry",
    "manage_product_expiry",
    "dispose_expired_stock",
    "view_product_profit",
    "view_product_potential_profit",
    "export_expiry_report",
    "export_product_profit_report",
    "view_customers",
    "manage_customers",
    "view_customer_balance",
    "record_customer_payment",
    "adjust_customer_balance",
    "archive_customer",
    "view_expenses",
    "create_expense",
    "edit_expense",
    "void_expense",
    "manage_expense_categories",
    "view_suppliers",
    "manage_suppliers",
    "create_purchase",
    "view_purchases",
    "record_supplier_payment",
    "create_purchase_return",
    "view_supplier_balance",
    "view_purchase_costs",
    "view_sales_reports",
    "view_expense_reports",
    "view_inventory_reports",
    "view_customer_reports",
    "view_supplier_reports",
    "view_profit",
    "export_reports",
    "manage_receipt_templates",
    "edit_business_branding",
    "download_receipt_pdf",
    "share_receipt_pdf",
    "use_sabi",
    "use_sabi_sales",
    "use_sabi_expenses",
    "use_sabi_purchases",
    "ask_sabi_business_questions",
    "ask_sabi_profit_questions",
    "edit_business_settings",
    "manage_staff",
    "manage_roles",
    "view_staff_activity",
    "approve_sensitive_actions",
    "view_branch",
    "switch_branch",
    "manage_branch_operations",
    "view_notifications",
    "manage_notification_preferences",
    "view_low_stock_alerts",
    "view_customer_debt_alerts",
    "view_supplier_payment_alerts",
    "view_approval_notifications",
    "view_end_of_day_alerts",
    "view_daily_summary",
    "view_weekly_report",
    "receive_push_notifications",
    "send_customer_reminder_draft",
    "view_staff_notifications",
  ],
  cashier: [
    "create_sale",
    "view_own_sales",
    "view_sale_details",
    "share_receipt",
    "print_receipt",
    "apply_discount",
    "view_products",
    "view_product_expiry",
    "view_customers",
    "manage_customers",
    "record_customer_payment",
    "download_receipt_pdf",
    "share_receipt_pdf",
    "use_sabi",
    "use_sabi_sales",
    "ask_sabi_business_questions",
    "view_branch",
    "manage_branch_operations",
    "view_notifications",
    "view_low_stock_alerts",
    "view_approval_notifications",
    "view_end_of_day_alerts",
    "view_daily_summary",
    "receive_push_notifications",
  ],
  staff: [
    "view_branch",
    "manage_branch_operations",
  ],
  stock_keeper: [
    "view_products",
    "manage_products",
    "archive_product",
    "adjust_stock",
    "view_inventory_movements",
    "view_cost_price",
    "manage_categories",
    "manage_units",
    "view_product_expiry",
    "manage_product_expiry",
    "dispose_expired_stock",
    "export_expiry_report",
    "view_suppliers",
    "manage_suppliers",
    "create_purchase",
    "view_purchases",
    "record_supplier_payment",
    "create_purchase_return",
    "view_supplier_balance",
    "view_purchase_costs",
    "view_inventory_reports",
    "view_supplier_reports",
    "export_reports",
    "use_sabi",
    "use_sabi_purchases",
    "ask_sabi_business_questions",
    "view_branch",
    "manage_branch_operations",
    "view_notifications",
    "view_low_stock_alerts",
    "receive_push_notifications",
  ],
  accountant: [
    "view_own_sales",
    "view_all_sales",
    "view_sale_details",
    "view_products",
    "view_cost_price",
    "view_product_expiry",
    "view_product_profit",
    "view_product_potential_profit",
    "export_expiry_report",
    "export_product_profit_report",
    "view_customers",
    "view_customer_balance",
    "record_customer_payment",
    "view_expenses",
    "create_expense",
    "edit_expense",
    "void_expense",
    "manage_expense_categories",
    "view_suppliers",
    "view_purchases",
    "record_supplier_payment",
    "view_supplier_balance",
    "view_purchase_costs",
    "view_sales_reports",
    "view_expense_reports",
    "view_inventory_reports",
    "view_customer_reports",
    "view_supplier_reports",
    "view_profit",
    "export_reports",
    "use_sabi",
    "use_sabi_expenses",
    "ask_sabi_business_questions",
    "ask_sabi_profit_questions",
    "view_branch",
    "manage_branch_operations",
    "view_notifications",
    "view_customer_debt_alerts",
    "view_supplier_payment_alerts",
    "view_daily_summary",
    "view_weekly_report",
    "receive_push_notifications",
    "send_customer_reminder_draft",
  ],
};

export type ResolvedMembership = {
  role: string;
  roleId: string;
  isOwner: boolean;
  status: string;
  permissions: Set<AppPermissionCode>;
};
ROLE_DEFAULTS.admin = [...ROLE_DEFAULTS.manager];

const LEGACY_PERMISSION_ALIASES: Record<string, AppPermissionCode> = {
  view_branches: "view_branch",
  switch_branches: "switch_branch",
  view_all_branch_reports: "view_combined_reports",
  manage_branch_staff: "assign_staff_to_branches",
};

export function resolvePermissions(input: {
  isOwner: boolean;
  role?: string;
  roleId?: string;
  permissions?: unknown;
}): Set<AppPermissionCode> {
  if (input.isOwner || input.role === "owner" || input.roleId === "owner") {
    return new Set(APP_PERMISSIONS);
  }
  const roleKey = (input.roleId || input.role || "cashier").toLowerCase();
  const fromDoc = Array.isArray(input.permissions)
    ? input.permissions
        .filter((permission): permission is string => typeof permission === "string")
        .map(
          (permission) =>
            LEGACY_PERMISSION_ALIASES[permission] ?? permission,
        )
        .filter(
          (permission): permission is AppPermissionCode =>
            (APP_PERMISSIONS as readonly string[]).includes(permission),
        )
    : [];
  if (fromDoc.length > 0) return new Set(fromDoc);
  return new Set(ROLE_DEFAULTS[roleKey] ?? ROLE_DEFAULTS.cashier);
}

export function membershipHasPermission(
  membership: ResolvedMembership,
  permission: AppPermissionCode | string,
): boolean {
  if (membership.status !== "active") return false;
  if (membership.isOwner || membership.role === "owner") return true;
  return membership.permissions.has(permission as AppPermissionCode);
}
